services:
  - type: web
    name: edupredictors
    runtime: python
    buildCommand: pip install -r requirements-web.txt
    startCommand: gunicorn api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
